export const actionTypes = {
  CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD ',
  REQUEST_CATS_START: 'REQUEST_CATS_START',
  REQUEST_CATS_SUCCESS: 'REQUEST_CATS_SUCCESS',
  REQUEST_CATS_FAILURE: 'REQUEST_CATS_FAILURE',
};
